fixed misleading description of geoserver deployment
dcs4cop/xcube-geodb pull request #49
Opened 2023-01-04 11:49 UTC by thomasstorm

2023-01-04 12:39 UTC, AliceBalfanz commented on docker/geoserver/Dockerfile
> +# Example for version 1.0.3:
```suggestion
# Example how to push a new docker image to quay.io for version 1.0.3:
```

2023-01-04 12:41 UTC, AliceBalfanz requested changes
Please see my comments in the review. Please also investigate why CI test for nbs :)

2023-01-04 16:16 UTC, AliceBalfanz commented
Hi Thomas, you manually updated the geoserver docker image - however we have a github action which does this automatically, as it seams in the CI:
![image](https://user-images.githubusercontent.com/23457217/210599776-ac353b8e-5bb2-451e-aa4a-7ad33b48a86e.png)
We should either delete the gha for this (not my preferred option, because we would move a step back) , or use it in the future.

2023-01-04 17:10 UTC, thomasstorm commented
> 

No - this action builds the [xcube-geodb-backend](https://quay.io/repository/bcdev/xcube-geodb-backend) image. That's different from the GeoServer image.

2023-01-09 07:40 UTC, AliceBalfanz approved these changes
Thanks for the response to my question :)

2023-01-16 13:56 UTC, merged